#!/bin/bash -xe

rm -rf boot
mkdir boot
mkdir boot/tools

./scripts/dtc/dtc arch/powerpc/boot/dts/p1020rdb.dts -I dts -o boot/p1020rdbT.dtb -O dtb
./scripts/dtc/dtc arch/powerpc/boot/dts/p1022ds_32b.dts -I dts -o boot/p1022ds_32bT.dtb -O dtb
./scripts/dtc/dtc arch/powerpc/boot/dts/p1022ds_36b.dts -I dts -o boot/p1022ds_36bT.dtb -O dtb

cp .config boot/configT.txt
cp arch/powerpc/boot/uImage boot/uImageT

make -C rvs_library clean
make -C rvs_library_test clean
make -C rvs_library
make -C rvs_library_test

pushd rvs_module
make K=$PWD clean
make K=$PWD
popd

tar xvzf ../L1_L2_kernel_modules.tar.gz 
pushd L2_and_Branching
cat > Makefile <<EOF
K ?= /lib/modules/$(shell uname -r)/build

obj-m += L2-disabler.o
obj-m += L-dis.o
obj-m += B-dis.o

modules clean:
	make -C \$(K) M=\$(PWD) \$@

EOF
make K=$PWD clean
make K=$PWD
popd


tar cvzf 312_kernel_test.tar.gz lib/modules/ boot/ \
   rvs_module/*.ko \
   L2_and_Branching/*.ko \
   rvs_library/librvs.a \
   rvs_library/librvs.h \
   rvs_library_test/rvs_library_test
cp 312_kernel_test.tar.gz /tmp


