#!/bin/bash -xe
# Cross-compile the kernel and modules
# To do a deep clean beforehand, use "git clean -x -f -d .".

export GITREP=$PWD
cd ../linux-tools
export LINUX_TOOLS=$PWD
export CROSS_CC=$PWD/bin/powerpc-eabi-gcc
cd $GITREP

rm -rf lib/modules/* boot
mkdir boot

/usr/bin/make \
   ARCH=powerpc CROSS_COMPILE=$LINUX_TOOLS/bin/powerpc-eabi- \
   INSTALL_MOD_PATH=$GITREP INSTALL_PATH=$GITREP -j4 \
   uImage modules modules_install

./scripts/dtc/dtc arch/powerpc/boot/dts/p1020rdb.dts -I dts -o boot/p1020rdbT.dtb -O dtb
./scripts/dtc/dtc arch/powerpc/boot/dts/p1022ds_32b.dts -I dts -o boot/p1022ds_32bT.dtb -O dtb
./scripts/dtc/dtc arch/powerpc/boot/dts/p1022ds_36b.dts -I dts -o boot/p1022ds_36bT.dtb -O dtb

cp .config boot/configT.txt
cp arch/powerpc/boot/uImage boot/uImageT
cp System.map boot/

pushd rvs_module
   make K=$GITREP ARCH=powerpc CROSS_COMPILE=$LINUX_TOOLS/bin/powerpc-eabi-
popd


