#!/bin/bash -xe
# Cross-compile the kernel: the first step of the build.
# To do a deep clean beforehand, use "git clean -x -f -d .".


export ROOT=$PWD
pushd ../linux-tools
   export LINUX_TOOLS=$PWD
popd

rm -rf lib/modules/*
/usr/bin/make \
   ARCH=powerpc CROSS_COMPILE=$LINUX_TOOLS/bin/powerpc-eabi- \
   INSTALL_MOD_PATH=$ROOT INSTALL_PATH=$ROOT uImage modules modules_install


